#!/bin/bash

# By default, we assume this will be installed in the cloud-client
# bin directory. If it isn't you'll want to point to your cloud-client
# install here.
CLOUDCLIENT=$(cd `dirname $0` && echo `pwd`/../bin/cloud-client.sh)
#CLOUDCLIENT=/path/to/cloud-client.sh

usage="Usage: `basename $0` cloud.host.name"

if [ $# -lt 1 ]; then

    echo $usage
    exit 1
fi

HOST=$1

DATESTAMP=`date +%s` 

CONFFILE=/tmp/vm-list.${DATESTAMP}.conf

echo "
vws.factory=${HOST}:8443
" > $CONFFILE
$CLOUDCLIENT --conf $CONFFILE --status
rm $CONFFILE
